FUSED_LAYERNORM: False
DATA:
  IMG_SIZE: 224
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  DROP_RATE: 0.0
  NUM_CLASSES: 512
  USE_CHECKPOINT: False
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
    PATCH_SIZE: 4
    MLP_RATIO: 4.
    QKV_BIAS: True
    APE: False
    PATCH_NORM: True
    use_checkpoint: False
    PRETRAINED_WINDOW_SIZES: [0, 0, 0, 0]